[package]
name = "ocl-example-rgb2gray"
version = "0.0.2"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]

[dependencies]
ocl = "*"
image = "*"
time = "*"
find_folder = "*"
colorify = "*"

[replace]
"ocl-core:0.2.3" = { git = "https://github.com/cogciprocate/ocl-core" }
