[package]
name = "ocl"
version = "0.12.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL bindings and interfaces for Rust."
documentation = "http://doc.cogciprocate.com/ocl/ocl/index.html"
homepage = "https://github.com/cogciprocate/ocl"
repository = "https://github.com/cogciprocate/ocl"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT/Apache-2.0"
exclude = ["target/*", "*.png", "bak/*"]
categories = ["asynchronous", "concurrency", "science"]

[features]
event_debug_print = []
kernel_debug_print = []
kernel_debug_sleep = []
opencl_version_1_1 = ["ocl-core/opencl_version_1_1"]
opencl_version_1_2 = ["ocl-core/opencl_version_1_2"]
opencl_version_2_0 = ["ocl-core/opencl_version_2_0"]
opencl_version_2_1 = ["ocl-core/opencl_version_2_1"]

# Use OpenCL event callbacks for task unparking and other event forwarding
# purposes.
#
# Disabling this will cause each task to block its thread instead of returning
# `Async::NotReady` to its executor and will be a less performant solution.
# Disable only if your platform has issues with event callbacks (old/non-compliant
# hardware).
event_callbacks = []

# Allows use of unstable experimental types and functions for to reading from
# and writing to buffers.
experimental_async_rw = []


default = ["event_callbacks", "opencl_version_1_1", "opencl_version_1_2"]


[dependencies]
# ocl-core = "0.3"
ocl-core = { version = "0.3.2", git = "https://github.com/cogciprocate/ocl-core" }
# ocl-core = { version = "0.3.2", path = "/home/nick/src/github.com/cogciprocate/ocl-core" }
num = "0.1"
libc = "0.2"
enum_primitive = "0.1"
bitflags = "0.8"

futures = "0.1"

[dev-dependencies]
find_folder = "0.3"
colorify = "0.2"
time = "0.1"
rand = "0.3"
chrono = "0.2"
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"
# tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
lazy_static = "0.2"
ocl-extras = { version = "0.1", path = "ocl-extras" }

# [replace]
# # "cl-sys:0.2.1" = { git = "https://github.com/cogciprocate/cl-sys" }
# # "ocl-core:0.3.2" = { git = "https://github.com/cogciprocate/ocl-core" }
# # "ocl-core:0.3.2" = { path = "/home/nick/src/github.com/cogciprocate/ocl-core" }
# "ocl-core:0.3.2" = { path = "../ocl-core" }

[workspace]
members = ["ocl-extras", "examples/images", "examples/images_safe_clamp",
	"examples/opencl_2_1"]