[package]
name = "ocl"
version = "0.11.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL bindings and interfaces for Rust."
documentation = "http://doc.cogciprocate.com/ocl/ocl/index.html"
homepage = "https://github.com/cogciprocate/ocl"
repository = "https://github.com/cogciprocate/ocl"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT/Apache-2.0"
exclude = ["target/*", "*.png", "bak/*"]


[features]
kernel_debug_print = []
kernel_debug_sleep = []

# Useful on platforms (such as PoCL) that have trouble with fill. Creates a
# temporary zeroed `Vec` in host memory during creation and writes zeros from
# there instead of calling `clEnqueueFillBuffer`:
buffer_no_fill = []


# [dependencies.ocl-core]
# git = "https://github.com/cogciprocate/ocl-core"
# path = "/home/nick/src/github.com/cogciprocate/ocl-core"

[dependencies]
ocl-core = "0.2"
num = "0.1"
libc = "0.2"
enum_primitive = "0.1"
bitflags = "0.5"


[dev-dependencies]
find_folder = "0.3"
colorify = "0.2"
time = "0.1"
rand = "0.3"


[replace]
"ocl-core:0.2.3" = { git = "https://github.com/cogciprocate/ocl-core" }
