[package]
name = "cl-sys"
version = "0.1.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL bindings for Rust."
documentation = "http://doc.cogciprocate.com/cl-sys/cl-sys/index.html"
homepage = "https://github.com/cogciprocate/cl-sys"
repository = "https://github.com/cogciprocate/cl-sys"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT"
exclude = ["target/*", "*.png", "bak/*"]

[dependencies]
enum_primitive = "0.1"
libc = "0.2"
