[package]
name = "cl-sys"
version = "0.2.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL FFI bindings."
documentation = "http://doc.cogciprocate.com/cl_sys/cl_sys"
homepage = "https://github.com/cogciprocate/cl-sys"
repository = "https://github.com/cogciprocate/cl-sys"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT"
exclude = ["target/*", "bak/*"]

[dependencies]
libc = "0.2"
