[package]
name = "ocl"
version = "0.12.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL bindings and interfaces for Rust."
documentation = "http://doc.cogciprocate.com/ocl/ocl/index.html"
homepage = "https://github.com/cogciprocate/ocl"
repository = "https://github.com/cogciprocate/ocl"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT/Apache-2.0"
exclude = ["target/*", "*.png", "bak/*"]
# categories = ["asynchronous", "concurrency", "science"]

[features]
event_debug_print = []
kernel_debug_print = []
kernel_debug_sleep = []
opencl_version_1_1 = ["ocl-core/opencl_version_1_1"]
opencl_version_1_2 = ["ocl-core/opencl_version_1_2"]
opencl_version_2_0 = ["ocl-core/opencl_version_2_0"]
opencl_version_2_1 = ["ocl-core/opencl_version_2_1"]

# Causes a map command with either write flag set to block regardless of
# whether or not the command was enqueued asynchronously or not.
#
# This corrects a somewhat rare issue on some platforms (CPU only?) when
# mapping commands, out-of-order queues, and event synchronization are used
# together.
#
# The performance implications are probably negligible when
# `CL_MAP_WRITE_INVALIDATE_REGION` (aka.
# `MapFlags::write_invalidate_region()`) is set but may be significant if
# `CL_MAP_WRITE` (aka. `MapFlags::write()`) is used.
#
# Run the `device_check` example to determine if this option is necessary on
# your device.
always_block_on_map_writes = []

# Useful on platforms (such as PoCL) that have trouble with fill. Creates a
# temporary zeroed `Vec` in host memory during creation and writes zeros from
# there instead of calling `clEnqueueFillBuffer`:
buffer_no_fill = []

# Use exclusively polling instead of OpenCL callbacks for task unparking.
disable_event_callbacks = []

default = ["opencl_version_1_1", "opencl_version_1_2"]


[dependencies]
# ocl-core = "0.3"
ocl-core = { version = "0.3.2", path = "/home/nick/src/github.com/cogciprocate/ocl-core" }
num = "0.1"
libc = "0.2"
enum_primitive = "0.1"
bitflags = "0.8"

futures = "0.1"

[dev-dependencies]
find_folder = "0.3"
colorify = "0.2"
time = "0.1"
rand = "0.3"
chrono = "0.2"
futures = "0.1"
futures-cpupool = "0.1"
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }

[replace]
# "cl-sys:0.2.1" = { git = "https://github.com/cogciprocate/cl-sys" }
# "ocl-core:0.3.2" = { git = "https://github.com/cogciprocate/ocl-core" }
# "ocl-core:0.3.2" = { path = "/home/nick/src/github.com/cogciprocate/ocl-core" }