[package]
name = "cl-sys"
version = "0.2.1"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL FFI bindings."
documentation = "http://doc.cogciprocate.com/cl_sys/cl_sys"
homepage = "https://github.com/cogciprocate/cl-sys"
repository = "https://github.com/cogciprocate/cl-sys"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT/Apache-2.0"
exclude = ["target/*", "bak/*"]
build = "build.rs"
# categories = ["api-bindings", "external-ffi-bindings", "asynchronous", "science"]

[dependencies]
libc = "0.2"
