[package]
name = "ocl-core"
version = "0.2.2"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "Rusty and conventional OpenCL API."
documentation = "http://doc.cogciprocate.com/ocl_core/ocl_core/index.html"
homepage = "https://github.com/cogciprocate/ocl-core"
repository = "https://github.com/cogciprocate/ocl-core"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT/Apache-2.0"
exclude = ["target/*", "bak/*"]

[dependencies]
cl-sys = "0.2"
rand = "0.3"
num = "0.1"
libc = "0.2"
enum_primitive = "0.1"
bitflags = "0.5"

[dev-dependencies]
colorify = "0.2"