[package]
name = "images"
version = "0.1.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]

[dependencies]
ocl = { path = "../../" }
colorify = "*"
image = "*"

[replace]
"ocl-core:0.3.2" = { git = "https://github.com/cogciprocate/ocl-core" }
